
name: Full CI

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]
# paths:
# - "*"
# - "!README.md" <-- don't rebuild on doc change

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains three jobs to verify different hosts
  setup_mac:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup MacOS env
        run: ./Tools/environment_install/install-prereqs-mac.sh
        shell: bash

      - name: Update submodules
        run: git submodule update --recursive --init
        shell: bash

  setup_win:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Windows env
        run: .\Tools\environment_install\install-prereqs-windows.ps1
        shell: powershell

      - name: Update submodules
        run: git submodule update --recursive --init
        shell: powershell

  setup_ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Ubuntu env
        run: ./Tools/environment_install/install-prereqs-ubuntu.sh
        shell: bash

      - name: Update submodules
        run: git submodule update --recursive --init
        shell: bash

  build_mac:
  # The type of runner that the job will run on
    needs: setup_mac
    runs-on: macos-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

    # Runs a single command using the runners shell
      - name: Build_CI_MacOS
        run: ./Tools/scripts/build_ci.sh
        shell: bash

  build_win:
  # The type of runner that the job will run on
    needs: setup_win
    runs-on: windows-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

    # Runs a single command using the runners shell
      - name: Build_CI_Win
        run: .\Tools\scripts\build_ci.ps1
        shell: powershell

  build_ubuntu:
  # The type of runner that the job will run on
    needs: setup_ubuntu
    runs-on: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

    # Runs a single command using the runners shell
      - name: Build_CI_Ubuntu
        run: ./Tools/scripts/build_ci.sh
        shell: bash
